### ISSUE TITLE
Shareable URLs

### ISSUE THREAD

**Issue by kettle11** [brandonfcohen1/openparkingmap#10]
Great project!

I suspect the project would be used a lot more if it were easy to share a URL for a specific city or location. Something like `https://www.openparkingmap.com/#philadelphia` that I could embed in an article would be incredibly helpful!

**Comment by brandonfcohen1** [comment]
good idea! To make it work for any city I'd have to use a geocoder that might not always hit, but would at least work for major cities, or could hardcode some values in.

**Comment by kettle11** [comment]
Another thought is that if there's a way to pull the latitude / longitude of the center of the screen and the current zoom level then that data could always be encoded in the URL.

Then sharing a specific perspective would be just be as easy as sharing the URL.

**Comment by brandonfcohen1** [comment]
good call! I can work on that

**Comment by brandonfcohen1** [comment]
FYI @kettle11

**Comment by kettle11** [comment]
@brandonfcohen1 Thank you! This is excellent and makes this website all the more useful.
