### ISSUE TITLE
Filter for All, Public, or Private parking

### ISSUE THREAD

**Issue by rikahlberg** [brandonfcohen1/openparkingmap#19]
I'd love to have a filter to only show All parking lots, only lots that are Public, or only lots that are Private. There are tags for all of that in OSM, but I don't have the tools to break that out. (Oh, and big props for the "download geojson" link - that makes it really nice to be able to pull the data and use it in other maps!)

**Comment by brandonfcohen1** [comment]
I like this. Will give it a shot!

**Comment by CurtisGreen** [comment]
@rikahlberg I believe this has been addressed with this PR: https://github.com/brandonfcohen1/openparkingmap/pull/25

Let me know if there are other filters you think would be useful
