### ISSUE TITLE
Missing a lot of car parking

### ISSUE THREAD

**Issue by philam** [brandonfcohen1/openparkingmap#2]
Hi there,

Great project! Just starting a thread here to talk about what's missing.

Most of the car parking that I know in OSM (at least in Australia) doesn't currently have a tag specifying that it is a surface carpark. Moreover, there seems to be a general understanding that unless it is specifically tagged as underground or part of some building, it's assumed to be surface.

Obviously this isn't ideal and over time this needs to be fixed. However, until then, about 80% of car parking isn't showing up on this map.

Here's an example of central Melbourne. First image is OpenParkingMap, the second is overpass with a simple `amenity=parking` tag.

![](https://user-images.githubusercontent.com/6771240/227860797-6a853e18-66ae-4b84-afa6-9bdb75f1acd2.png)

![](https://user-images.githubusercontent.com/6771240/227860819-add9b8f9-8eec-4772-91d0-ef22271fc84b.png)

As you can see it's quite a big difference.

I would like to see OpenParkingMap actively exclude non-surface parking tags, and include any blank tags - i.e. `parking=*`

Anyway that's my two cents worth :)

**Comment by brandonfcohen1** [comment]
Changed the query to include all parking _except_ these tags:

```
  const restrictTags = [
    "underground",
    "multi-storey",
    "sheds",
    "garage_boxes",
    "carport",
  ];
```

The area in Melbourne you showed looks much better!
<img width="951" alt="image" src="https://user-images.githubusercontent.com/2308834/228100047-e47ec32b-ebc2-4422-985b-38175f1d528c.png">
